### ISSUE TITLE
Failed loading 'libopencv_videoio.so'

### ISSUE THREAD

**Issue by prabhuultra** [vdechenaux/PhpWebcamMjpeg#1]
GET /mjpeg.php - Uncaught FFI\Exception: Failed loading 'libopencv_videoio.so' in C:\Users\**\Downloads\PhpWebcamMjpeg-master\vendor\vdechenaux\webcam\src\Webcam.php:36

**Comment by vdechenaux** [comment]
Hey,

The project requires OpenCV as mentioned here https://github.com/vdechenaux/PhpWebcam#requirements

I don't know how to install it on Windows but you'll probably found your answer on the Internet ;)
